import {NextResponse} from 'next/server'
import ExcelJS from 'exceljs'
import {createClient} from '@/lib/supabase/crew-server'
import {allocateTime} from '@/lib/crew-time'
export async function GET(){
 const s=await createClient();const {data:{user}}=await s.auth.getUser();if(!user)return new NextResponse('Unauthorized',{status:401})
 const {data:profile}=await s.from('profiles').select('role,approved').eq('id',user.id).single();if(!profile?.approved||profile.role!=='admin')return new NextResponse('Forbidden',{status:403})
 const queries=await Promise.all([s.from('work_sessions').select('*').order('started_at'),s.from('break_sessions').select('*'),s.from('workplace_transitions').select('*'),s.from('events').select('id,name,timezone'),s.from('profiles').select('id,full_name'),s.from('shifts').select('*'),s.from('workplaces').select('id,name'),s.from('responsible_assignments').select('*'),s.from('check_ins').select('user_id,event_id,status'),s.from('briefings').select('*'),s.from('briefing_acknowledgements').select('*'),s.from('tasks').select('*'),s.from('task_assignments').select('*')])
 if(queries.some(q=>q.error))return new NextResponse('Exportgegevens konden niet worden geladen.',{status:503})
 const [sessions,breaks,transitions,events,people,shifts,workplaces,leads,checkins,briefings,acks,tasks,assignments]=queries.map(q=>q.data||[]) as [NonNullable<typeof queries[0]['data']>,NonNullable<typeof queries[1]['data']>,NonNullable<typeof queries[2]['data']>,NonNullable<typeof queries[3]['data']>,NonNullable<typeof queries[4]['data']>,NonNullable<typeof queries[5]['data']>,NonNullable<typeof queries[6]['data']>,NonNullable<typeof queries[7]['data']>,NonNullable<typeof queries[8]['data']>,NonNullable<typeof queries[9]['data']>,NonNullable<typeof queries[10]['data']>,NonNullable<typeof queries[11]['data']>,NonNullable<typeof queries[12]['data']>]
 // PostgREST caps rows; fail visibly rather than silently issuing incomplete payroll.
 if(queries.some(q=>(q.data?.length||0)>=1000))return new NextResponse('Deze export vereist paginering; geen gedeeltelijk bestand aangemaakt.',{status:409})
 let rows;try{rows=allocateTime(sessions.map(x=>({...x,workplace_id:shifts.find(y=>y.id===x.shift_id)?.workplace_id||null})),breaks,transitions,Date.now())}catch{return new NextResponse('Tijdregistraties vereisen correctie voor export.',{status:409})}
 const wb=new ExcelJS.Workbook(),ws=wb.addWorksheet('Werkpleksegmenten')
 const headers=['Date','Event','Employee','Workplace','Role','Responsible Lead','Shift Start','Shift End','Gross Duration','Regular Break','Excess Break','Net Hours','Overtime','Briefing Confirmed','Task Package Confirmed','Check-in Status']
 ws.columns=headers.map(h=>({header:h,key:h,width:24}))
 for(const row of rows){const event=events.find(e=>e.id===row.eventId);const shift=shifts.find(x=>x.user_id===row.userId&&x.event_id===row.eventId&&x.workplace_id===row.workplaceId&&Date.parse(x.scheduled_start)<=row.start&&Date.parse(x.scheduled_end)>row.start);const zone=event?.timezone||'Europe/Brussels';const date=(n:number)=>new Intl.DateTimeFormat('nl-BE',{timeZone:zone,dateStyle:'short',timeStyle:'short'}).format(n)
 const required=briefings.filter(b=>b.event_id===row.eventId&&b.required&&(!b.workplace_id||b.workplace_id===row.workplaceId))
 const own=assignments.filter(a=>a.user_id===row.userId&&tasks.some(t=>t.id===a.task_id&&t.event_id===row.eventId&&(!t.workplace_id||t.workplace_id===row.workplaceId)))
 ws.addRow({'Date':date(row.start),'Event':event?.name,'Employee':people.find(p=>p.id===row.userId)?.full_name,'Workplace':workplaces.find(w=>w.id===row.workplaceId)?.name,'Role':shift?.role_name,'Responsible Lead':leads.filter(l=>l.workplace_id===row.workplaceId).map(l=>people.find(p=>p.id===l.user_id)?.full_name||l.user_id).join(', '),'Shift Start':shift?date(Date.parse(shift.scheduled_start)):'','Shift End':shift?date(Date.parse(shift.scheduled_end)):'','Gross Duration':row.grossSeconds/3600,'Regular Break':row.regularBreakSeconds/3600,'Excess Break':row.excessBreakSeconds/3600,'Net Hours':row.netSeconds/3600,'Overtime':'Niet vastgesteld','Briefing Confirmed':required.every(b=>acks.some(a=>a.briefing_id===b.id&&a.user_id===row.userId&&a.version===b.version))?'Ja':'Nee','Task Package Confirmed':own.length?own.every(a=>a.status==='COMPLETED')?'Ja':'Nee':'N.v.t.','Check-in Status':checkins.some(c=>c.user_id===row.userId&&c.event_id===row.eventId&&c.status==='approved')?'approved':'Niet goedgekeurd'})
 }
 ws.getRow(1).font={bold:true};ws.views=[{state:'frozen',ySplit:1}];ws.autoFilter={from:'A1',to:'P1'}
 const notes=wb.addWorksheet('Toelichting');notes.addRow(['Tijden zijn per werkpleksegment; totalen worden niet nogmaals als datarij toegevoegd.']);notes.addRow(['Numerieke duurkolommen zijn decimale uren. Eerste 60 minuten pauze per medewerker/event zijn betaald.']);notes.addRow(['Overwerk is niet berekend: een goedgekeurde overwerkdefinitie ontbreekt.']);notes.addRow(['Actieve sessies zijn een momentopname; controleer registraties voor loonverwerking.'])
 const buffer=await wb.xlsx.writeBuffer();const {error}=await s.rpc('upt_audit_export');if(error)return new NextResponse('Export kon niet worden geaudit.',{status:503})
 return new NextResponse(new Uint8Array(buffer),{headers:{'content-type':'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet','content-disposition':'attachment; filename="uptilldawn-uren.xlsx"','cache-control':'private, no-store'}})
}
