'use server'
import { createClient } from '@/lib/supabase/server'
import { supabaseAdmin } from '@/lib/supabase/admin'
import { revalidatePath } from 'next/cache'

async function adminUser(){const s=await createClient();const {data:{user}}=await s.auth.getUser();if(!user)return null;const {data}=await s.from('user_roles').select('role').eq('user_id',user.id);if(!(data??[]).some((r:any)=>r.role==='admin'))return null;return user}
const defaults=['Ticket Scan','Guest List','Artists','Merch','Bar / Toog','Backstage Management','Allrounder','Setup','Breakdown']
export async function createEvent(fd:FormData){const u=await adminUser();if(!u)return;const name=String(fd.get('name')||'').trim(),start=String(fd.get('start_at')||''),end=String(fd.get('end_at')||'');if(!name||!start||!end)return;const {data,error}=await supabaseAdmin.from('events').insert({name,venue:String(fd.get('venue')||'').trim()||null,address:String(fd.get('address')||'').trim()||null,start_at:new Date(start).toISOString(),end_at:new Date(end).toISOString(),checkin_radius_m:Number(fd.get('radius')||100),created_by:u.id}).select('id').single();if(!error&&data)await supabaseAdmin.from('workplaces').insert(defaults.map((n,i)=>({event_id:data.id,name:n,sort_order:i})));revalidatePath('/events');revalidatePath('/workplaces')}
export async function addWorkplace(fd:FormData){const u=await adminUser();if(!u)return;const event_id=String(fd.get('event_id')||''),name=String(fd.get('name')||'').trim();if(event_id&&name)await supabaseAdmin.from('workplaces').insert({event_id,name});revalidatePath('/workplaces')}
export async function addEventMember(fd:FormData){const u=await adminUser();if(!u)return;await supabaseAdmin.from('event_members').upsert({event_id:String(fd.get('event_id')),user_id:String(fd.get('user_id')),event_role:'employee'},{onConflict:'event_id,user_id'});revalidatePath('/events');revalidatePath('/shifts')}
export async function assignResponsible(fd:FormData){const u=await adminUser();if(!u)return;const workplace_id=String(fd.get('workplace_id')),user_id=String(fd.get('user_id'));const {data:w}=await supabaseAdmin.from('workplaces').select('event_id').eq('id',workplace_id).single();if(w)await supabaseAdmin.from('responsible_assignments').upsert({event_id:w.event_id,workplace_id,user_id,assigned_by:u.id},{onConflict:'workplace_id,user_id'});revalidatePath('/workplaces')}
export async function createShift(fd:FormData){const u=await adminUser();if(!u)return;const workplace_id=String(fd.get('workplace_id')),user_id=String(fd.get('user_id'));const {data:w}=await supabaseAdmin.from('workplaces').select('event_id').eq('id',workplace_id).single();if(!w)return;await supabaseAdmin.from('shifts').insert({event_id:w.event_id,workplace_id,user_id,role_name:String(fd.get('role_name')||'Crew'),scheduled_start:new Date(String(fd.get('start'))).toISOString(),scheduled_end:new Date(String(fd.get('end'))).toISOString(),overlap_allowed:fd.get('overlap_allowed')==='on'});revalidatePath('/shifts')}
export async function setAccountStatus(fd:FormData){const u=await adminUser();if(!u)return;const id=String(fd.get('user_id')),status=String(fd.get('status'));if(!['approved','rejected','suspended','pending'].includes(status))return;await supabaseAdmin.from('user_profiles').update({account_status:status,approved_by:status==='approved'?u.id:null,approved_at:status==='approved'?new Date().toISOString():null}).eq('id',id);revalidatePath('/personnel')}
