insert into public.role_ui_rules
  (role,feature_key,label,group_key,visible,enabled,condition_key,sort_order,settings)
values
 ('admin','overview','Overzicht','navigation',true,true,'always',10,'{}'::jsonb),
 ('admin','events','Evenementen','navigation',true,true,'always',20,'{}'::jsonb),
 ('admin','operations','Werkuren','navigation',true,true,'always',30,'{}'::jsonb),
 ('admin','shifts','Shift''s','navigation',true,true,'always',40,'{}'::jsonb),
 ('admin','workplaces','Werkplekken','navigation',true,true,'always',50,'{}'::jsonb),
 ('admin','tasks','Taken','navigation',true,true,'always',60,'{}'::jsonb),
 ('admin','briefings','Briefing','navigation',true,true,'always',70,'{}'::jsonb),
 ('admin','personnel','Personeel & goedkeuringen','navigation',true,true,'always',80,'{}'::jsonb),
 ('admin','chat','Chat''s','navigation',true,true,'always',90,'{}'::jsonb),
 ('admin','crew','Personeel','navigation',true,true,'always',100,'{}'::jsonb),
 ('admin','incidents','Help','navigation',true,true,'always',110,'{}'::jsonb),
 ('admin','exports','Excel','navigation',true,true,'always',120,'{}'::jsonb),
 ('admin','settings','Instellingen','navigation',true,true,'always',130,'{}'::jsonb),
 ('responsible_lead','overview','Overzicht','navigation',true,true,'always',10,'{}'::jsonb),
 ('responsible_lead','operations','Mijn werkuren','navigation',true,true,'event_active',20,'{}'::jsonb),
 ('responsible_lead','events','Evenementen','navigation',true,true,'always',30,'{}'::jsonb),
 ('responsible_lead','shifts','Shift''s','navigation',true,true,'assigned_event',40,'{}'::jsonb),
 ('responsible_lead','tasks','Taken','navigation',true,true,'shift_active',50,'{}'::jsonb),
 ('responsible_lead','briefings','Briefing','navigation',true,true,'assigned_event',60,'{}'::jsonb),
 ('responsible_lead','workplaces','Werkplekken','navigation',true,true,'assigned_workplace_role',70,'{}'::jsonb),
 ('responsible_lead','chat','Chat''s','navigation',true,true,'always',80,'{}'::jsonb),
 ('responsible_lead','crew','Personeel','navigation',true,true,'always',90,'{}'::jsonb),
 ('responsible_lead','incidents','Help','navigation',true,true,'shift_active',100,'{}'::jsonb),
 ('staff','overview','Overzicht','navigation',true,true,'always',10,'{}'::jsonb),
 ('staff','operations','Mijn werkuren','navigation',true,true,'shift_active',20,'{}'::jsonb),
 ('staff','events','Evenementen','navigation',true,true,'always',30,'{}'::jsonb),
 ('staff','shifts','Mijn shift''s','navigation',true,true,'assigned_event',40,'{}'::jsonb),
 ('staff','briefings','Briefing','navigation',true,true,'assigned_event',50,'{}'::jsonb),
 ('staff','workplaces','Werkplekken','navigation',false,false,'assigned_workplace_role',60,'{}'::jsonb),
 ('staff','tasks','Taken','navigation',true,true,'shift_active',70,'{}'::jsonb),
 ('staff','chat','Chat''s','navigation',true,true,'always',80,'{}'::jsonb),
 ('staff','crew','Personeel','navigation',true,true,'always',90,'{}'::jsonb),
 ('staff','incidents','Help','navigation',true,true,'shift_active',100,'{}'::jsonb)
on conflict (role,feature_key) do update
set label=excluded.label,
    group_key=excluded.group_key,
    visible=excluded.visible,
    enabled=excluded.enabled,
    condition_key=excluded.condition_key,
    sort_order=excluded.sort_order,
    settings=excluded.settings,
    updated_at=now();
