'use client'
import { useEffect,useState } from 'react'
import { createClient } from '@/lib/supabase/crew-client'
import { enqueue } from '@/lib/crew-queue'
import type { Tables } from '@/types/crew-database'
export function ChatClient({channels,userId}:{channels:Tables<'chat_channels'>[];userId:string}){
 const [selected,setSelected]=useState(channels[0]?.id||''),[messages,setMessages]=useState<Tables<'messages'>[]>([]),[body,setBody]=useState(''),[status,setStatus]=useState(''),[busy,setBusy]=useState(false)
 useEffect(()=>{if(!selected)return;const s=createClient();let alive=true;async function load(){const {data,error}=await s.from('messages').select('*').eq('channel_id',selected).order('created_at',{ascending:false}).limit(100);if(alive){if(error)setStatus('Berichten konden niet worden geladen.');else setMessages((data||[]).reverse())}}void load();const channel=s.channel(`crew-chat-${selected}`).on('postgres_changes',{event:'*',schema:'public',table:'messages',filter:`channel_id=eq.${selected}`},()=>void load()).subscribe();const timer=setInterval(()=>void load(),10000);return()=>{alive=false;clearInterval(timer);void s.removeChannel(channel)}},[selected])
 return <section className="space-y-4"><select aria-label="Chatkanaal" className="w-full rounded-xl border bg-background p-3" value={selected} onChange={e=>{setSelected(e.target.value);setMessages([])}}>{channels.map(c=><option value={c.id} key={c.id}>{c.name||c.kind}</option>)}</select><div className="space-y-3">{messages.map(m=><article key={m.id} className="rounded-xl border p-3"><p className="whitespace-pre-wrap">{m.moderated_at?'Bericht verwijderd door administrator':m.body}</p><p className="text-xs text-muted-foreground">{m.sender_id===userId?'Jij':'Crew'} · {new Date(m.created_at).toLocaleString('nl-BE')}</p></article>)}</div><form className="flex gap-3" onSubmit={async e=>{e.preventDefault();if(busy||!body.trim()||!selected)return;setBusy(true);try{await enqueue(userId,'message',{channel_id:selected,body:body.trim()});setBody('');setStatus('Bericht bewaard voor verzending.')}catch{setStatus('Bericht kon niet worden bewaard.')}finally{setBusy(false)}}}><input aria-label="Bericht" required maxLength={4000} value={body} onChange={e=>setBody(e.target.value)} className="min-w-0 flex-1 rounded-xl border bg-background p-3"/><button disabled={busy||!selected} className="rounded-xl bg-violet-600 p-3">Versturen</button></form><p role="status">{status}</p></section>
}
